### ISSUE TITLE
Not getting OTP 

### ISSUE THREAD

**Issue by Dattar** [MSG91/sendotp-android#15]
2019-09-09 17:24:55.685 23873-23930/com.msg91.sendotp.sample.test I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
2019-09-09 17:24:55.690 23873-23930/com.msg91.sendotp.sample.test D/NetworkSecurityConfig: Using Network Security Config from resource configuration_http debugBuild: true
2019-09-09 17:24:55.696 23873-23930/com.msg91.sendotp.sample.test W/System.err: java.io.IOException: Cleartext HTTP traffic to control.msg91.com not permitted
2019-09-09 17:24:55.696 23873-23930/com.msg91.sendotp.sample.test W/System.err: at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
2019-09-09 17:24:55.696 23873-23930/com.msg91.sendotp.sample.test W/System.err: at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
2019-09-09 17:24:55.696 23873-23930/com.msg91.sendotp.sample.test W/System.err: at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
2019-09-09 17:24:55.696 23873-23930/com.msg91.sendotp.sample.test W/System.err: at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
2019-09-09 17:24:55.696 23873-23930/com.msg91.sendotp.sample.test W/System.err: at com.msg91.sendotpandroid.library.internal.ApiService.openConnection(ApiService.java:67)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at com.msg91.sendotpandroid.library.internal.ApiService.getOkHttpClient(ApiService.java:41)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at com.msg91.sendotpandroid.library.internal.ApiService.getResponse(ApiService.java:164)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at com.msg91.sendotpandroid.library.internal.ApiService.generateRequest(ApiService.java:202)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at com.msg91.sendotpandroid.library.internal.VerificationMethod$1.doInBackground(VerificationMethod.java:94)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at com.msg91.sendotpandroid.library.internal.VerificationMethod$1.doInBackground(VerificationMethod.java:86)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at android.os.AsyncTask$2.call(AsyncTask.java:333)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-09-09 17:24:55.697 23873-23930/com.msg91.sendotp.sample.test W/System.err: at java.lang.Thread.run(Thread.java:764)
2019-09-09 17:24:55.821 23873-23873/com.msg91.sendotp.sample.test E/Verification: Verification initialization failed: Request Unsuccessful Try Again

**Comment by iamrajendra** [comment]
We are  working on the issue, get back to you very soon

**Comment by iamrajendra** [comment]
Hi, make sure that you are using a correct credential 
sendotp_key ="?"

**Comment by Dattar** [comment]
Hi,

issue did't close.

i am getting this error in the VerificationActivity. and I have checked my
sendotp_key = 253727A68MGdH1Jye5c2463a1 which is right.

2019-09-11 15:57:54.156 26755-26755/com.msg91.sendotp.sample.test
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.msg91.sendotp.sample.test, PID: 26755
    java.lang.NoClassDefFoundError: Failed resolution of:
Lorg/apache/http/conn/util/InetAddressUtils;
        at
com.msg91.sendotpandroid.library.IPConverter.getIPAddress(IPConverter.java:109)
        at
com.msg91.sendotp.sample.VerificationActivity.getIp(VerificationActivity.java:104)
        at
com.msg91.sendotp.sample.VerificationActivity.createVerification(VerificationActivity.java:74)
        at
com.msg91.sendotp.sample.VerificationActivity.initiateVerification(VerificationActivity.java:147)
        at
com.msg91.sendotp.sample.VerificationActivity.initiateVerification(VerificationActivity.java:133)
        at
com.msg91.sendotp.sample.VerificationActivity.onCreate(VerificationActivity.java:53)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
        at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
        at
android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class
"org.apache.http.conn.util.InetAddressUtils" on path: DexPathList[[zip file
"/data/app/com.msg91.sendotp.sample.test-xQ2DTSlWbUZE6osl496aUQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.msg91.sendotp.sample.test-xQ2DTSlWbUZE6osl496aUQ==/lib/arm64,
/system/lib64, /system/vendor/lib64]]
        at
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at
com.msg91.sendotpandroid.library.IPConverter.getIPAddress(IPConverter.java:109)
        at
com.msg91.sendotp.sample.VerificationActivity.getIp(VerificationActivity.java:104)
        at
com.msg91.sendotp.sample.VerificationActivity.createVerification(VerificationActivity.java:74)
        at
com.msg91.sendotp.sample.VerificationActivity.initiateVerification(VerificationActivity.java:147)
        at
com.msg91.sendotp.sample.VerificationActivity.initiateVerification(VerificationActivity.java:133)
        at
com.msg91.sendotp.sample.VerificationActivity.onCreate(VerificationActivity.java:53)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
        at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
        at
android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
