### ISSUE TITLE
App Crash on VerificationActivity

### ISSUE THREAD

**Issue by Dattar** [MSG91/sendotp-android#16]
2019-09-11 15:57:54.156 26755-26755/com.msg91.sendotp.sample.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.msg91.sendotp.sample.test, PID: 26755
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/util/InetAddressUtils;
        at com.msg91.sendotpandroid.library.IPConverter.getIPAddress(IPConverter.java:109)
        at com.msg91.sendotp.sample.VerificationActivity.getIp(VerificationActivity.java:104)
        at com.msg91.sendotp.sample.VerificationActivity.createVerification(VerificationActivity.java:74)
        at com.msg91.sendotp.sample.VerificationActivity.initiateVerification(VerificationActivity.java:147)
        at com.msg91.sendotp.sample.VerificationActivity.initiateVerification(VerificationActivity.java:133)
        at com.msg91.sendotp.sample.VerificationActivity.onCreate(VerificationActivity.java:53)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.conn.util.InetAddressUtils" on path: DexPathList[[zip file "/data/app/com.msg91.sendotp.sample.test-xQ2DTSlWbUZE6osl496aUQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.msg91.sendotp.sample.test-xQ2DTSlWbUZE6osl496aUQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.msg91.sendotpandroid.library.IPConverter.getIPAddress(IPConverter.java:109) 
        at com.msg91.sendotp.sample.VerificationActivity.getIp(VerificationActivity.java:104) 
        at com.msg91.sendotp.sample.VerificationActivity.createVerification(VerificationActivity.java:74) 
        at com.msg91.sendotp.sample.VerificationActivity.initiateVerification(VerificationActivity.java:147) 
        at com.msg91.sendotp.sample.VerificationActivity.initiateVerification(VerificationActivity.java:133) 
        at com.msg91.sendotp.sample.VerificationActivity.onCreate(VerificationActivity.java:53) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6762) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by iamrajendra** [comment]
To resolve the issue.  A remote session is required,

**Comment by iamrajendra** [comment]
please update your SDK to version 1.0

**Comment by jobinjj** [comment]
Got any solution? same problem on sdk version 1.1

**Comment by IrshadAndroid** [comment]
Thank you for your feedback, the above issue is already resolved on previous versions.  kindly use updated  [1.3.1](https://github.com/MSG91/sendotp-android)
