### ISSUE TITLE
Crashes app after mobile verification completed and other messages received on device while app is runnig

### ISSUE THREAD

**Issue by dkdilipkumar** [MSG91/sendotp-android#21]
java.lang.RuntimeException: Unable to start receiver com.msg91.sendotpandroid.library.GetSMSBroadcast: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.msg91.sendotpandroid.library.internal.VerificationMethod.handleSmsCallBack(android.content.Intent)' on a null object reference
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3389)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.msg91.sendotpandroid.library.internal.VerificationMethod.handleSmsCallBack(android.content.Intent)' on a null object reference
        at com.msg91.sendotpandroid.library.GetSMSBroadcast.onReceive(GetSMSBroadcast.java:14)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3380)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by iamrajendra** [comment]
.autoVerification(false) should be false because Google Play’s new policy Removing the READ_SMS permission

for more information please follow this link 
https://play.google.com/about/privacy-security-deception/permissions/

Detail about the OTP SDK implementation is 
https://github.com/MSG91/sendotp-android/blob/master/README.md

**Comment by IrshadAndroid** [comment]
For a better experience and want to read SMS from OTP use the latest version of SDK [1.3.1](https://github.com/MSG91/sendotp-android)
