### ISSUE TITLE
App Crashing while initialisation of Verification. ( Androidx Target Api-29 )

### ISSUE THREAD

**Issue by Gangerkka** [MSG91/sendotp-android#23]
While initialisation of Verification Class App is crashing with Exception 
` java.lang.IllegalArgumentException: configure sendotp.key in manifest file.
        at com.msg91.sendotpandroid.library.internal.VerificationMethod.<init>(VerificationMethod.java:71)
        at com.msg91.sendotpandroid.library.internal.SmsVerificationFactory.create(SmsVerificationFactory.java:11)
        at com.msg91.sendotpandroid.library.SendOtpVerification.createSmsVerification(SendOtpVerification.java:14)
        at com.netgo.viewmodels.OtpViewModel.initializeForOtp(OtpViewModel.kt:31)
        at com.netgo.view.fragments.OtpInput.onNext(OtpInput.kt:68)
        at com.netgo.databinding.FragmentOtpInputBindingImpl._internalCallbackOnClick(FragmentOtpInputBindingImpl.java:140)
        at com.netgo.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:5619)
        at android.view.View$PerformClick.run(View.java:22298)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)`
However, I have already configured it in manifest file
`<application
        android:name=".App"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:usesCleartextTraffic="true"
        android:theme="@style/AppTheme"
        tools:replace="android:allowBackup"
        tools:ignore="GoogleAppIndexingWarning"
        tools:targetApi="m">

        <meta-data android:name="sendotp.key" android:value="@string/sendotp_key"/>  </application>`

`@Inject
    @OtpInputScope
    lateinit var verificationListener:VerificationListener

    lateinit var sendOTPConfig :SendOTPConfig
    lateinit var verification:Verification

    fun initializeForOtp(obs: OtpObservable){
        sendOTPConfig=SendOtpVerification
            .config(obs.countryCode+obs.mobile)
            .expiry(obs.otpExpiry)
            .senderId(obs.senderId)
            .otplength(obs.otpLength)
            .message(obs.msg)
            .otp(obs.otp)
            .build()
        verification=SendOtpVerification.createSmsVerification(sendOTPConfig,verificationListener)

    }`

**Comment by Gangerkka** [comment]
`try {
            ApplicationInfo ai = mContext.getPackageManager().getApplicationInfo
                    (mContext.getPackageName(), PackageManager.GET_META_DATA);
            Bundle bundle = ai.metaData;
            this.authKey = bundle.getString("sendotp.key");
        } catch (Exception e) {
            Log.e(TAG, "Dear developer. Don't forget to configure <meta-data android:name=\"sendotp.key\" android:value=\"testValue\"/> in your AndroidManifest.xml file.");
            throw new IllegalArgumentException("configure sendotp.key in manifest file.");
        }`


In your code you are throwing your `IllegalArgumentException("configure sendotp.key in manifest file.")` 
But i guess the the real exception is something else,Maybe your `mContext` or `ai` is not getting initialised.

**Comment by IrshadAndroid** [comment]
Thank you for your valuable feedback, given issue has been resolved on new version 1.3.1 .kindly use the new version of SDK [1.3.1](https://github.com/MSG91/sendotp-android)
