### ISSUE TITLE
Unable to launch the application in android with following error

### ISSUE THREAD

**Issue by lalitha12** [MSG91/sendotp-android#3]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.pyramid.loginapp, PID: 5378
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.pyramid.loginapp/com.example.pyramid.loginapp.MainActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class in.walkover.sendotpsample.CountrySpinner
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                   Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class in.walkover.sendotpsample.CountrySpinner
                   Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class in.walkover.sendotpsample.CountrySpinner
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "in.walkover.sendotpsample.CountrySpinner" on path: DexPathList[[zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/base.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_resources_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/lib/x86, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:606)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                      at com.example.pyramid.loginapp.MainActivity.onCreate(MainActivity.java:39)
E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:7009)
                      at android.app.Activity.performCreate(Activity.java:7000)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                  	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.example.pyramid.loginapp-AWVcIQBOK8usi_XnbSGAbQ==/split_lib_resources_apk.apk
                      at dalvik.system.DexFile.openDexFileNative(Native Method)
                      at dalvik.system.DexFile.openDexFile(DexFile.java:353)
                      at dalvik.system.DexFile.<init>(DexFile.java:100)
                      at dalvik.system.DexFile.<init>(DexFile.java:74)
                      at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
                      at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
                      at dalvik.system.DexPathList.<init>(DexPathList.java:157)
                      at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
                      at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                      at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
                      at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
                      at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
                      at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:693)
                      at android.app.LoadedApk.getClassLoader(LoadedApk.java:727)
                      at android.app.LoadedApk.getResources(LoadedApk.java:954)
                      at android.app.ContextImpl.createAppContext(ContextImpl.java:2270)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5639)
                      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                      		... 6 more

**Comment by IrshadAndroid** [comment]
Hi, Thank-you for report us. This issue is resolved you can use the latest version . Use The given sample and run it as it is. It will resolve your issue.
