### ISSUE TITLE
React Native app crash 

### ISSUE THREAD

**Issue by dimaportenko** [MSG91/sendotp-android#31]
I'm adding a dependency 
```
implementation 'com.msg91.sendotpandroid.library:library:1.3.3'
```
and getting the following crash 
```
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.fourqube.vimanmart, PID: 31469
    java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in base.apk)
        at okhttp3.JavaNetCookieJar.saveFromResponse(JavaNetCookieJar.java:45)
        at com.facebook.react.modules.network.ReactCookieJarContainer.saveFromResponse(ReactCookieJarContainer.java:36)
        at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.kt:207)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:86)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

any ideas on how to solve it?

**Comment by dimaportenko** [comment]
I solved it by adding `okhttp` dependency 
```
implementation 'com.msg91.sendotpandroid.library:library:1.3.3'
implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.4.1'
```
