### ISSUE TITLE
Crash in Android 4 Devices

### ISSUE THREAD

**Issue by akshayshenoy38** [MSG91/sendotp-android#34]
Hi Team,
        Im getting crash in Android 4 (minimum sdk 17) Devices when I trigger sendOtp, in sdk versions 17 and 18.

 was getting crash when I trigger SendOTP.getInstance().trigger().initiate();

Following is the log details.

E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at a.a.a.a.d.a.a()
        at a.a.a.a.b.a.a(:20)
        at a.a.a.a.b.a.b(:19)
        at a.a.a.a.b.c.initiate()
        at com.criyagen.activities.Login.createVerification(Login.java:675)
        at com.criyagen.activities.Login.registerMessage91Otp(Login.java:655)
        at com.criyagen.activities.Login.access$700(Login.java:85)
        at com.criyagen.activities.Login$11.onResponse(Login.java:617)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$1.run(DefaultCallAdapterFactory.java:83)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)

![image (2)](https://user-images.githubusercontent.com/30587680/91040977-d386d580-e62c-11ea-93e9-4212d7d57d0d.png)

Thanks and Regards,

**Comment by AdityaIsHere** [comment]
Hi @akshayshenoy38 
can you let me know the snippet's place "SendOTP.getInstance().trigger().initiate();", where you have called it in?

**Comment by AdityaIsHere** [comment]
hi @akshayshenoy38 
please check with the latest version of the library
And please update us so that this issue will be closed!

**Comment by akshayshenoy38** [comment]
Hi Sir,
      If I Use Version 1.3.8, Now Crash is not there, but when I try logging in, im not getting response in Pixel Emulators. Response is not coming, Does it not work on Emulators?
